# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21
yarn_mappings=1.21+build.3
loader_version=0.16.2
fabric_version=0.102.0+1.21

# Mod Properties
mod_version=2.8.1
maven_group=draylar.inmis
archives_base_name=inmis

# Dependencies
trinkets_version=3.10.0
cloth_config_version=15.0.130
shulker_box_tooltip_version=5.1.0+1.21.1
mod_menu_version=11.0.1
